/// <reference types="bun" />
/**
 * Writes the hosting files that hold config values into `public/` before dev and build, so
 * they are never typed by hand: Cloudflare Pages' `_redirects` (root to the default locale)
 * and `.well-known/security.txt` (RFC 9116). Both outputs are git-ignored.
 *
 *   bun scripts/generate-public-files.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { PUBLIC_PATHS, type Site, site } from "@bookmark-scout/config";

/** Cloudflare Pages `_redirects`: the root goes to the default locale. */
export function redirectsFile(model: Site = site): string {
    return [
        "# Cloudflare Pages redirects, generated by scripts/generate-public-files.ts from config.",
        "# The root page also has a meta refresh for other hosts.",
        `/  ${model.url.path(model.locales.default)}  302`,
        "",
    ].join("\n");
}

/** RFC 9116 security.txt. Renew `[security_txt] expires` in config/web.toml before it lapses. */
export function securityTxtFile(model: Site = site): string {
    return [
        `# ${model.name} security contact (RFC 9116), generated from config/project.toml and config/web.toml.`,
        `Contact: ${model.contact.mailto("security")}`,
        `Contact: ${model.repo.newSecurityAdvisory}`,
        `Expires: ${model.securityTxt.expires}`,
        `Preferred-Languages: ${model.locales.supported.join(", ")}`,
        `Canonical: ${model.securityTxt.url}`,
        `Policy: ${model.repo.file("SECURITY.md")}`,
        "",
    ].join("\n");
}

/** Output path (under `public/`) and contents of every generated file. */
export const PUBLIC_FILES: Record<string, () => string> = {
    _redirects: () => redirectsFile(),
    [PUBLIC_PATHS.securityTxt.slice(1)]: () => securityTxtFile(),
};

if (import.meta.main) {
    const publicDir = resolve(import.meta.dir, "..", "public");
    for (const [path, render] of Object.entries(PUBLIC_FILES)) {
        const file = join(publicDir, path);
        mkdirSync(dirname(file), { recursive: true });
        writeFileSync(file, render());
        console.log(`public/${path}`);
    }
}
